import { Report, SentimentData, SectorAlert } from './types';

export const mockReports: Report[] = [
  {
    id: '1',
    title: '半导体供应链中的AI革命',
    ticker: 'NVDA',
    sector: '科技',
    summary: '深入探讨生成式AI在未来24个月内如何迫使工厂限制和逻辑密度进行全面重新架构。AI模型预测产量效率将提升40%。',
    content: '## 核心观点\n在过去的六个月里，我们观察到半导体供应链内部发生了前所未有的范式重构。随着生成式AI（GenAI）对计算资源需求的呈指数级增长，传统的芯片设计周期与掩膜制造流程已显现出明显的瓶颈。\n\n## 供给侧的系统性限制\n我们的多模态AI抓取了全球前三大晶圆代工厂（TSMC, Samsung Foundry, Intel）的采购订单与设备交付周期数据。数据显示，极紫外（EUV）光刻机的交付周期已拉长至破纪录的18个月，而高级封装（如CoWoS）的日均产能缺口仍在扩大。\n\n但是，引入AI辅助设计的EDA工具正在带来革命。我们监控到某些无晶圆厂设计公司（Fabless）通过采用AI算法进行自动布局与布线（P&R），成功将流片周期缩短了近30%。这不仅抵消了部分物理制造端的延迟，更为下一代3nm及以下工艺的良率提升提供了数据飞轮支撑。\n\n## 需求侧：数据中心扩建浪潮的衍生效应\n不仅仅是GPU，整个数据中心架构（包括高带宽内存HBM、光模块、以及液冷系统）都在经历价值重估。我们独家聚合了北美八大云服务商（CSP）的资本支出（CapEx）前瞻指引，并使用NLP技术解析其财报电话会议。结果表明，“AI基础设施”相关的词频提及率环比上升了120%。\n\n## 投资建议与风险提示\n我们维持对该板块的**增持**评级。重点关注那些在高级封装材料、硅光子导入以及AI辅助测试设备中占据垄断地位的中流企业。\n\n*主要风险：地缘政治造成的供应链摩擦，以及终端AI应用变现不及预期导致的数据中心投资砍单。*',
    impact: 'positive',
    date: '2026-06-08',
    isPremium: true,
  },
  {
    id: '5',
    title: '固态电池突破对产业链估值的重塑',
    ticker: '300750.SZ',
    sector: '新能源',
    summary: '宁德时代最新专利数据分析显示，全固态电池量产节点可能比市场预期提前。AI预测这将使头部企业享有至少两年的超额利润期。',
    content: '## 行业拐点逼近\n我们利用机器视觉分析了最近两个季度全球范围内提交的超过4,000份电池相关专利图纸与参数。结果显示，硫化物固态电解质的空气稳定性与锂金属负极的界面阻抗问题，在几家头部企业（以宁德时代为代表）的研究中已经取得了实质性突破。这标志着全固态电池从“实验室概念”向“工程化量产”的拐点正在逼近。\n\n## 产业链价值重估\n固态电池的商业化并不是简单的替代，而是对整个产业链利润池的重新分配：\n\n1.  **电解液与隔膜环节受损**：传统的液态电解质和隔膜需求将被极大地压缩。我们的估值模型已经开始下调相关龙头企业的长期利润率预期。\n2.  **正负极材料迭代升级**：超高镍正极和硅基/锂金属负极迎来爆发。能够提供高纯度固态电解质（如硫化锂）的新材料公司将获得溢价。\n3.  **设备端更新换代需求**：为了适应不同的工艺路线（如干法电极），锂电设备制造商将迎来新一轮设备更新换代的资本性支出周期。\n\n## 情绪面异动监控\n在过去72小时内，我们追踪到散户论坛和机构研报中关于“固态电池量产”的情绪得分从中性急剧上升至极度看多（Score: 92/100）。这与头部企业近期频繁增加的相关领域高端人才招聘数据高度吻合。\n\n## 策略建议\n我们建议对现有新能源汽车产业链持仓进行结构性调整。重点配置具有深度固态电池技术储备的电池主机厂，并在材料端寻找拥有核心专利的初创/转型企业。当前市场对这些技术节点的提前兑现仍定价不足。',
    impact: 'positive',
    date: '2026-06-08',
    isPremium: true,
  },
  {
    id: '2',
    title: '可再生能源补贴悬崖：第三季度展望',
    ticker: 'ICLN',
    sector: '能源',
    summary: '分析欧盟和美国市场即将发生的政策变化。针对立法草案的AI情绪分析表明，太阳能信贷延期的可能性为65%，但风能面临阻力。',
    impact: 'neutral',
    date: '2026-06-07',
    isPremium: true,
  },
  {
    id: '6',
    title: '高端白酒周期见底的量价模型预测',
    ticker: '600519.SH',
    sector: '可选消费',
    summary: '结合高频批价数据和经销商库存AI监测，贵州茅台批价已在关键支撑位企稳。中秋国庆双节备货期可能迎来估值修复。',
    impact: 'neutral',
    date: '2026-06-07',
    isPremium: true,
  },
  {
    id: '7',
    title: '自动驾驶FSD入华对本土车企的算力挤压',
    ticker: '002594.SZ',
    sector: '汽车',
    summary: '比亚迪等本土巨头正加速端到端模型部署。算力储备差异将导致高阶智驾体验分化，二线车企将面临严重的淘汰危机。',
    impact: 'negative',
    date: '2026-06-06',
    isPremium: true,
  },
  {
    id: '8',
    title: '游戏版号常态化下的出海优势评估',
    ticker: '0700.HK',
    sector: '互联网',
    summary: '腾讯新游海外流水增速连续三季度超预期。AI分析海外玩家评论和社群热度显示，其在射击和SLG品类已建立深厚的数据壁垒。',
    impact: 'positive',
    date: '2026-06-06',
    isPremium: true,
  },
  {
    id: '3',
    title: '后期临床试验中的生物科技利润压缩',
    ticker: 'XBI',
    sector: '医疗保健',
    summary: '资金成本严重限制了中型生物科技公司的发展空间。我们的模型识别出14项脆弱资产，有望在年底前进行并购或重组。',
    impact: 'negative',
    date: '2026-06-06',
    isPremium: true,
  },
  {
    id: '4',
    title: '非必需消费品支出转向',
    sector: '零售',
    summary: '实时信用卡数据抓取结合社交情绪表明，消费正从奢侈品向体验类大幅轮动。航空公司和酒店的远期预订量出现史无前例的增长。',
    impact: 'positive',
    date: '2026-06-05',
    isPremium: true,
  }
];

export const mockSentiment: SentimentData[] = [
  { time: '09:30', score: 45 },
  { time: '10:00', score: 48 },
  { time: '10:30', score: 42 },
  { time: '11:00', score: 35 },
  { time: '11:30', score: 38 },
  { time: '12:00', score: 52 },
  { time: '12:30', score: 65 },
  { time: '13:00', score: 72 },
  { time: '13:30', score: 68 },
  { time: '14:00', score: 75 },
  { time: '14:30', score: 82 },
  { time: '15:00', score: 78 },
  { time: '15:30', score: 85 },
  { time: '16:00', score: 88 },
];

export const mockAlerts: SectorAlert[] = [
  { id: 'a1', sector: '科技', enabled: true, threshold: 80 },
  { id: 'a6', sector: '新能源 (A股)', enabled: true, threshold: 75 },
  { id: 'a2', sector: '医疗保健', enabled: false, threshold: 50 },
  { id: 'a7', sector: '白酒 (A股)', enabled: true, threshold: 65 },
  { id: 'a3', sector: '能源', enabled: true, threshold: 40 },
  { id: 'a8', sector: '互联网 (港股)', enabled: false, threshold: 85 },
  { id: 'a4', sector: '金融', enabled: true, threshold: 60 },
  { id: 'a5', sector: '非必需消费品', enabled: false, threshold: 70 },
];
